# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: run

  build:
    desc: "Build gurl binary"
    cmds:
      - bash scripts/version.sh
      - defer: git checkout internal/version/version.go
      - "{{.ENV}} go build -v -o bin/gurl{{.SUFFIX}} cmd/gurl/main.go"

  run:
    desc: "Compiles and runs gurl"
    cmds:
      - go run -v cmd/gurl/main.go {{.CLI_ARGS}}

  release:
    desc: "Build binaries for different architectures"
    cmds:
      - task: build
        vars:
          SUFFIX: "_darwin_amd64"
          ENV: "GOOS=darwin GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_darwin_arm64"
          ENV: "GOOS=darwin GOARCH=arm64"
      - task: build
        vars:
          SUFFIX: "_linux_amd64"
          ENV: "GOOS=linux GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_linux_arm64"
          ENV: "GOOS=linux GOARCH=arm64"
      - task: build
        vars:
          SUFFIX: "_windows_amd64.exe"
          ENV: "GOOS=windows GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_windows_arm64.exe"
          ENV: "GOOS=windows GOARCH=arm64"

  test:
    desc: "Run unit tests"
    cmds:
      - go test -v -cover ./...

  bundle:
    desc:
      Builds binaries for different architectures and bundles the 
      current directory into a gzipped tarball.
    deps:
      - release
    cmds:
      - tar -czvf gurl.tar.gz $(ls -a1 | grep -v "^\.\.$" | grep -v "^\.$")