# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: run

  build:
    cmds:
      - bash scripts/version.sh
      - defer: git checkout internal/version/version.go
      - "{{.ENV}} go build -v -o bin/gurl{{.SUFFIX}} cmd/gurl/main.go"

  run:
    cmds:
      - go run -v cmd/gurl/main.go {{.CLI_ARGS}}

  release:
    cmds:
      - task: build
        vars:
          SUFFIX: "_darwin_amd64"
          ENV: "GOOS=darwin GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_darwin_arm64"
          ENV: "GOOS=darwin GOARCH=arm64"
      - task: build
        vars:
          SUFFIX: "_linux_amd64"
          ENV: "GOOS=linux GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_linux_arm64"
          ENV: "GOOS=linux GOARCH=arm64"
      - task: build
        vars:
          SUFFIX: "_windows_amd64.exe"
          ENV: "GOOS=windows GOARCH=amd64"
      - task: build
        vars:
          SUFFIX: "_windows_arm64.exe"
          ENV: "GOOS=windows GOARCH=arm64"

  test:
    cmds:
      - go test -v -cover ./...