[book]
authors = ["zekroTJA"]
language = "en"
multilingual = false
src = "src"
title = "Goat"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
site-url = "/goat/"
additional-js = ["js/mermaid.min.js", "js/mermaid-init.js"]
