name: Build Artifacts
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "*"
  #   paths-ignore:
  #     - "**.md"

jobs:
  build_artifacts:
    name: Build Artifcats
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos:
          - linux
          - windows
          - darwin
        goarch:
          - amd64
          - arm64
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Infuse Version
        run: bash scripts/version.sh
      - name: Build Client (${{ matrix.goos }}-${{ matrix.goarch }})
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -v -o ./bin/goat-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/goat/main.go
      - name: Rename Windows Binary
        if: ${{ matrix.goos == 'windows' }}
        env:
          FNAME: ./bin/goat-${{ matrix.goos }}-${{ matrix.goarch }}
        run: mv ${{ env.FNAME }} ${{ env.FNAME }}.exe
      - name: Upload Artifcats
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.goos }}-${{ matrix.goarch }}
          path: ./bin/
          retention-days: 5