name: Linting

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  unit_tests:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.23"
      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Linting
        run: task lint
