name: Unit Tests

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: task test
  e2e:
    name: "End to End Tests"
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.20"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Unit Tests
        shell: bash
        run: task e2e
