name: Unit Tests

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Get dependencies
        run: go get ./...
      - name: Run Unit Tests
        run: go test -v -cover ./...