name: Unit Tests

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v1
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run Unit Tests
        run: task test